const ApiUrls = {
    FACULTY_DASHBOARD_URL : 'http://localhost:8000/faculty/pendingrequests',
    COMMITTEE_DASHBOARD_URL : 'http://localhost:8000/committee/pendingrequests',
    HOD_DASHBOARD_URL : 'http://localhost:8000/hod/pendingrequests',
    FACULTY_INBOX_URL : 'http://localhost:8000/faculty/previousrequests',
    COMMITTEE_INBOX_URL : 'http://localhost:8000/committee/previousrequests',
    HOD_INBOX_URL : 'http://localhost:8000/hod/previousrequests',
    FACULTY_PUBLICREQUESTS_URL : 'http://localhost:8000/faculty/publicrequests',
    COMMITTEE_TRANSACTIONS_URL : 'http://localhost:8000/committee/alltransactions' ,
    HOD_TRANSACTIONS_URL : 'http://localhost:8000/hod/alltransactions'  ,
    HOD_SENDEXCEL_URL : 'http://localhost:8000/hod/sendexcelsheet',
    REQUEST_REQUESTDETAILS_URL : 'http://localhost:8000/request/requestdetails',
    REQUEST_FILEDETAILS_URL : 'http://localhost:8000/request/filedetails',
    COMMITTEE_APPROVE_URL : 'http://localhost:8000/committee/approve',
    COMMITTEE_DISAPPROVE_URL : 'http://localhost:8000/committee/disapprove',
    HOD_APPROVE_URL : 'http://localhost:8000/hod/approve',
    HOD_DISAPPROVE_URL : 'http://localhost:8000/hod/disapprove',
    REQUEST_CREATEBUDGETREQUEST_URL : 'http://localhost:8000/request/createbudgetrequest',
    REQUEST_CREATEPUBLICREQUEST_URL : 'http://localhost:8000/request/createpublicrequest',
    REQUEST_CREATEPRIVATEREQUEST_URL : 'http://localhost:8000/request/createprivaterequest',
    USER_CHANGEPASSWORD_URL : 'http://localhost:8000/user/changepassword',
    USER_PROFILE_URL : 'http://localhost:8000/user/profile',
    USER_REGISTER_URL : 'http://localhost:8000/user/register',
    USER_CHECKEMAIL_URL : 'http://localhost:8000/user/checkemail',
    AUTHENTICATION_LOGIN_URL : 'http://localhost:8000/authentication/login',
    AUTHENTICATION_FORGOTPASSWORD_URL : 'http://localhost:8000/authentication/forgotpassword',
    AUTHENTICATION_CHECKOTP_URL : 'http://localhost:8000/authentication/checkotp',
    AUTHENTICATION_RESETPASSWORD_URL : 'http://localhost:8000/authentication/resetpassword',
    AUTHENTICATION_LOGOUT_URL : 'http://localhost:8000/authentication/logout',
    AUTHENTICATION_AUTHENTICATED_URL : 'http://localhost:8000/authentication/authenticated',
}

export default ApiUrls